
import Head from 'next/head'
import { ReactNode } from 'react'

// layouts
import LayoutNotApp from 'src/views/layouts/LayoutNotApp'
import { getAllProductsPublic } from 'src/services/product'
import { getAllProductTypes } from 'src/services/product-type'
import { TProduct } from 'src/types/product'
// ** Pages
import HomePage from 'src/views/pages/home'


interface TOptions {
  label: string
  value: string
  id: string
}

interface TProps {
  products: TProduct[],
  totalCount: number,
  productTypes: TOptions[]
  params: {
    limit: number
    page: number
    order: string
  }
}

export default function Home(props:TProps) {
  const {products, totalCount, params, productTypes} = props
  console.log("products", {products})

  return (
    <>
      <Head>
        <title>Shop Máy Tính</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HomePage  products={products} totalCount={totalCount} paramsServer={params} productTypesServer={productTypes} />
    </>
  )
}

export async function getServerSideProps() {
  const limit = 4
  const page = 1
  const order = "createdAt desc"
  try {
    const productTypes: TOptions[] = []
    await getAllProductTypes({ params: { limit: -1, page: -1 } })
      .then(res => {
        const data = res?.data.productTypes
        if (data) {
          data?.map((item: { name: string; _id: string, slug: string }) => {
            productTypes.push({ label: item.name, value: item.slug, id: item._id })
          })
        }
      })
    const res = await getAllProductsPublic(
      { params: { limit: limit, page: page, order:order} }
    )

    const data = res?.data

    return {
      props: {
        products: data?.products,
        totalCount: data?.totalCount,
        productTypes: productTypes,
        params: {
          limit,
          page,
          order,
        }
      }
    }
  } catch (error) {
    return {
      props: {
        products: [],
        totalCount: 0,
        params: {
          limit,
          page,
          order
        }
      }
    }
  }
}


Home.getLayout = (page: ReactNode) => <LayoutNotApp>{page}</LayoutNotApp>
Home.guestGuard = false
Home.authGuard = false